- name: Configure interfaces
  template: src=interfaces.j2 dest=/etc/network/interfaces
  notify: reboot server

- name: Update repositories cache and install depends
  apt: name={{ item }} update_cache=yes
  with_items:
   - lldpd
   - ifenslave
   - bridge-utils
   - vlan
   - vim

- name: Setup bonding module in Kernel
  command: modprobe bonding

- name: Setup .1q module in Kernel
  command: modprobe 8021q

