---
- hosts: leafs
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - cumulus_ports
    # - cumulus_common
    - cumulus_interfaces
    - cumulus_quagga
    - cumulus_lnv
    - cumulus_readonly

- hosts: spines
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - cumulus_ports
    # - cumulus_common
    - cumulus_interfaces
    - cumulus_quagga
    - cumulus_lnv
    - cumulus_readonly


#- hosts: internet
#  user: cumulus
#  become: yes
#  become_method: sudo
#  roles:
#    - ifupdown2


- hosts: l2_servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - ifupdown

- hosts: l3_servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - quagga_roh
    - ifupdown
