
# This command checks quagga before restarting it, just in case there are syntax
# errors. The dryrun command will have output if there are problems, so this
# short shell scripts fails and stops ansible if there is any output.
- name: check quagga
  shell: bash -c '[[ -z $(vtysh -f /etc/quagga/Quagga.conf --dryrun) ]]'

# This command actually restarts quagga. This command will actually drop all
# routes currently in progress, so this will interrupt networking currently in
# place.
- name: restart quagga
  service: name=quagga state=restarted

- name: reload quagga
  service: name=quagga state=reloaded

- name: enable quagga
  service: name=quagga state=started enabled=yes
